app_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_main_index

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: en|fr
