# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PLAYER, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        Symfony\Component\Security\Core\User\UserInterface: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users_in_memory:
            memory:
                users:
                    toto: { password: tata, roles: [ROLE_ADMIN] }
        users_in_database:
            entity:
                class: AppBundle\Entity\Player
                property: username
        users:
            chain:
                providers: [users_in_memory, users_in_database]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: users
            anonymous: ~
            switch_user: ~
            form_login:
                login_path: app_main_index
                check_path: app_security_login_check
                default_target_path: app_game_index
                username_parameter: _player_username
                password_parameter: _player_password
            logout:
                path: app_security_logout
                target: app_main_index
