# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.game.dictionaries:
        - '%kernel.root_dir%/Resources/data/test.txt'
        - '%kernel.root_dir%/Resources/data/words.txt'
        - '%kernel.root_dir%/Resources/data/words.xml'

services:

    app.game.loader.txt_file:
        class: AppBundle\Game\Loader\TextFileLoader

    app.game.loader.xml_file:
        class: AppBundle\Game\Loader\XmlFileLoader

    app.game.word_list:
        class: AppBundle\Game\WordList
        calls:
            - [addLoader, ['txt', '@app.game.loader.txt_file']]
            - [addLoader, ['xml', '@app.game.loader.xml_file']]
            - [loadDictionaries, ['%app.game.dictionaries%']]

    app.game.game_context:
        class: AppBundle\Game\GameContext
        arguments: ['@session']

    app.game.game_runner:
        class: AppBundle\Game\GameRunner
        arguments: ['@app.game.game_context', '@app.game.word_list']
