# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    ## Contact
    AppBundle\Contact\ContactMailer:
        arguments:
            $recipient: '%webmaster_mail%'
        autowire: true

    ## Player
    AppBundle\Player\PlayerFactory: ['@app.player.password']

    app.player.password:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ['@security.encoder_factory', getEncoder]
        arguments: [AppBundle\Entity\Player]
        public: false
